<?php

namespace Battis\BatchAction;

/**
 * Exceptions generated by Actions
 *
 * @author Seth Battis <seth@battis.net>
 */
class Action_Exception extends \Exception {

	const ACTION_FAILED = 1;
	const CIRCULAR_DEPENDENCY = 2;
	const FAILED_PREREQUISITE = 3;
	const SANDBOX_ERROR = 4;
	const PARAMETER_MISMATCH = 5;
	const FILE_NOT_FOUND = 6;
}